# Generated by Django 5.2.7 on 2026-09-07 06:59

import calculator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0058_remove_systemeventmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentrylinemodel',
            name='power',
        ),
        migrations.AddField(
            model_name='dataentrylinemodel',
            name='system_power',
            field=models.IntegerField(default=600, verbose_name='Solar system power'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='power_tariff',
            field=models.FloatField(default=calculator.models.get_power_tariff, verbose_name='Вартість за Кв'),
        ),
    ]
